apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-db-pv
  namespace: default
spec:
  storageClassName: nfs-storage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${nfsServer}
    path: ${hubDbPath}