apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-db-pv
  namespace: default
spec:
  storageClassName: nfs-storage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: storagenfsmlops.privatelink.file.core.windows.net
    path: /storagenfsmlops/nfs-share/bitnami/hubdb/data