apiVersion: v1
kind: PersistentVolume
metadata:
  name: userdata-pv
  namespace: default
spec:
  storageClassName: nfs-storage
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${nfsServer}
    path: ${userdataPath}