apiVersion: v1
kind: PersistentVolume
metadata:
  name: userdata-pv
  namespace: default
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /bitnami/userdata/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ${nodo1}  # ← nodo 1