# nfs-ganesha.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-server-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-ganesha-data
  namespace: nfs-server-storage
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ganesha-conf
  namespace: nfs-server-storage
data:
  ganesha.conf: |
    # Config de Ganesha para exportar /exports/bitnami como /bitnami (NFSv4)
    NFS_CORE_PARAM {
      NFS_Protocols = 4;
      Mount_Path_Pseudo = true;
    }
    EXPORT_DEFAULTS {
      Access_Type = RW;
      Squash = None;
    }

    # Requerido: backend de recuperación NFSv4 y carpeta persistente
    NFSv4 {
      RecoveryBackend = FSNG;
      RecoveryDir     = "/var/lib/nfs/ganesha";
      Graceless       = false;
      DomainName      = "localdomain";
    }

    EXPORT {
      Export_Id = 1;
      Path = "/exports/bitnami";
      Pseudo = "/bitnami";
      Protocols = 4;
      FSAL { Name = VFS; }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-ganesha
  namespace: nfs-server-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-ganesha
  template:
    metadata:
      labels:
        app: nfs-ganesha
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      initContainers:
        - name: prepare-dirs
          image: busybox:latest
          command: ["sh","-lc"]
          args:
            - |
              set -e
              # Export roots
              mkdir -p /exports/bitnami/hubdb/data
              mkdir -p /exports/bitnami/jenkins/home
              mkdir -p /exports/bitnami/minio/data
              mkdir -p /exports/bitnami/postgresql-jupyterhub/data
              mkdir -p /exports/bitnami/postgresql/data
              mkdir -p /exports/bitnami/userdata/data
              mkdir -p /exports/bitnami/jupyterhub/data
              chmod -R 0777 /exports
              # NFSv4 recovery dirs
              mkdir -p /var/lib/nfs/ganesha
              mkdir -p /run/ganesha
              chmod 700 /var/lib/nfs /var/lib/nfs/ganesha || true
          volumeMounts:
            - name: data
              mountPath: /exports
            - name: ganesha-varlib
              mountPath: /var/lib/nfs
            - name: ganesha-run
              mountPath: /run/ganesha
      containers:
        - name: ganesha
          image: hectorm/nfs-ganesha:latest
          securityContext:
            privileged: true
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
            - name: nfs-udp
              containerPort: 2049
              protocol: UDP
          volumeMounts:
            - name: data
              mountPath: /exports
            - name: ganesha-conf
              mountPath: /etc/ganesha/ganesha.conf
              subPath: ganesha.conf
            - name: ganesha-varlib
              mountPath: /var/lib/nfs
            - name: ganesha-run
              mountPath: /run/ganesha
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nfs-ganesha-data
        - name: ganesha-conf
          configMap:
            name: ganesha-conf
        - name: ganesha-varlib
          emptyDir: {}
        - name: ganesha-run
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-ganesha
  namespace: nfs-server-storage
spec:
  type: ClusterIP
  selector:
    app: nfs-ganesha
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
      protocol: TCP
    - name: nfs-udp
      port: 2049
      targetPort: 2049
      protocol: UDP
