apiVersion: batch/v1
kind: Job
metadata:
  name: nfs-test
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: nfs-test
          image: busybox:latest
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              echo "[INFO] Verificando puerto NFS..."
              nc -vz nfs-ganesha.nfs-server-storage.svc.cluster.local 2049 || exit 1
              echo "[INFO] Verificando soporte NFS..."
              cat /proc/filesystems | grep -E "nfs|nfs4" || echo "NFS no soportado"
              echo "[INFO] Creando punto de montaje /mnt..."
              mkdir -p /mnt
              echo "[INFO] Montando export /bitnami..."
              mount -t nfs -o vers=4.1,timeo=600,retrans=2 nfs-ganesha.nfs-server-storage.svc.cluster.local:/bitnami /mnt
              echo "[OK] Montaje exitoso. Contenido:"
              ls -l /mnt
              umount /mnt
              echo "[INFO] Desmontado correctamente."
