apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-jupyterhub
provisioner: nfs.csi.k8s.io
parameters:
  server: storagenfsmlops.privatelink.file.core.windows.net
  share: /storagenfsmlops/nfs-share/bitnami/jupyterhub/data
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=4.1
